import os
from dotenv import load_dotenv

load_dotenv()
CAMERA_URL = os.getenv('CAMERA_URL')
CONTROL_URL = os.getenv('CONTROL_URL')
DEADZONE_URL = os.getenv('DEADZONE_URL')

PLAYER_LABEL = "Player"
TEAM_LABEL = "Team"
POWERSLIDE_LABEL = "Powerslide"
AIR_ROLL_LABEL = "Air Roll"
BOOST_LABEL = "Boost"
JUMP_LABEL = "Jump"
BALL_CAM_LABEL = "Ball Cam"
BRAKE_LABEL = "Brake"
THROTTLE_LABEL = "Throttle"
DEADZONE_SHAPE_LABEL = "Deadzone Shape"
DEADZONE_LABEL = "Deadzone"
DODGE_DEADZONE_LABEL = "Dodge Deadzone"
AERIAL_SENSITIVITY_LABEL = "Aerial Sensitivity"
STEERING_SENSITIVITY_LABEL = "Steering Sensitivity"
LAST_UPDATED_LABEL = "Last Updated"
CAMERA_SHAKE_LABEL = "Camera Shake"
FOV_LABEL = "FOV"
HEIGHT_LABEL = "Height"
ANGLE_LABEL = "Angle"
DISTANCE_LABEL = "Distance"
STIFFNESS_LABEL = "Stiffness"
SWIVEL_SPEED_LABEL = "Swivel Speed"
TRANSITION_SPEED_LABEL = "Transition Speed"
BALL_CAMERA_LABEL = "Ball Camera"
PLAYER_ID = "Player"
TEAM_ID = "Team"
POWERSLIDE_ID = "powerslide"
AIR_ROLL_ID = "air_roll"
BOOST_ID = "boost"
JUMP_ID = "jump"
BALL_CAM_ID = "ball_cam"
BRAKE_ID = "brake"
THROTTLE_ID = "throttle"
DEADZONE_SHAPE_ID = "deadzone_shape"
DEADZONE_ID = "deadzone"
DODGE_DEADZONE_ID = "dodge_deadzone"
AERIAL_SENSITIVITY_ID = "aerial_sensitivity"
STEERING_SENSITIVITY_ID = "steering_sensitivity"
LAST_UPDATED_ID = "last_updated"
CAMERA_SHAKE_ID = "camera_shake"
FOV_ID = "fov"
HEIGHT_ID = "height"
ANGLE_ID = "angle"
DISTANCE_ID = "distance"
STIFFNESS_ID = "stiffness"
SWIVEL_SPEED_ID = "swivel_speed"
TRANSITION_SPEED_ID = "transition_speed"
BALL_CAMERA_ID = "ball_camera"
CAMERA_SETTINGS = "camera_settings"
DEADZONE_SETTINGS = "deadzone_settings"
CONTROLLER_SETTINGS = "controller_settings"
ID = "ID"
LABEL = "LABEL"

PLAYER = {ID: PLAYER_ID, LABEL: PLAYER_LABEL}
TEAM = {ID: TEAM_ID, LABEL: TEAM_LABEL}
POWERSLIDE = {ID: POWERSLIDE_ID, LABEL: POWERSLIDE_LABEL}
AIR_ROLL = {ID: AIR_ROLL_ID, LABEL: AIR_ROLL_LABEL}
BOOST = {ID: BOOST_ID, LABEL: BOOST_LABEL}
JUMP = {ID: JUMP_ID, LABEL: JUMP_LABEL}
BALL_CAM = {ID: BALL_CAM_ID, LABEL: BALL_CAM_LABEL}
BRAKE = {ID: BRAKE_ID, LABEL: BRAKE_LABEL}
THROTTLE = {ID: THROTTLE_ID, LABEL: THROTTLE_LABEL}
DEADZONE_SHAPE = {ID: DEADZONE_SHAPE_ID, LABEL: DEADZONE_SHAPE_LABEL}
DEADZONE = {ID: DEADZONE_ID, LABEL: DEADZONE_LABEL}
DODGE_DEADZONE = {ID: DODGE_DEADZONE_ID, LABEL: DODGE_DEADZONE_LABEL}
AERIAL_SENSITIVITY = {ID: AERIAL_SENSITIVITY_ID, LABEL: AERIAL_SENSITIVITY_LABEL}
STEERING_SENSITIVITY = {ID: STEERING_SENSITIVITY_ID, LABEL: STEERING_SENSITIVITY_LABEL}
LAST_UPDATED = {ID: LAST_UPDATED_ID, LABEL: LAST_UPDATED_LABEL}
CAMERA_SHAKE = {ID: CAMERA_SHAKE_ID, LABEL: CAMERA_SHAKE_LABEL}
FOV = {ID: FOV_ID, LABEL: FOV_LABEL}
HEIGHT = {ID: HEIGHT_ID, LABEL: HEIGHT_LABEL}
ANGLE = {ID: ANGLE_ID, LABEL: ANGLE_LABEL}
DISTANCE = {ID: DISTANCE_ID, LABEL: DISTANCE_LABEL}
STIFFNESS = {ID: STIFFNESS_ID, LABEL: STIFFNESS_LABEL}
SWIVEL_SPEED = {ID: SWIVEL_SPEED_ID, LABEL: SWIVEL_SPEED_LABEL}
TRANSITION_SPEED = {ID: TRANSITION_SPEED_ID, LABEL: TRANSITION_SPEED_LABEL}
BALL_CAMERA = {ID: BALL_CAMERA_ID, LABEL: BALL_CAMERA_LABEL}

CONTROLLER_CONSTANTS = [
    POWERSLIDE,
    AIR_ROLL,
    BOOST,
    JUMP,
    BALL_CAM,
    BRAKE,
    THROTTLE
]

DEADZONE_CONSTANTS = [
    DEADZONE_SHAPE,
    DEADZONE,
    DODGE_DEADZONE,
    AERIAL_SENSITIVITY,
    STEERING_SENSITIVITY,
    LAST_UPDATED,
]

CAMERA_CONSTANTS = [
    CAMERA_SHAKE,
    FOV,
    HEIGHT,
    ANGLE,
    DISTANCE,
    STIFFNESS,
    SWIVEL_SPEED,
    TRANSITION_SPEED,
    BALL_CAMERA,
    LAST_UPDATED
]
